# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
    push:
        branches: [main, beta]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn install --immutable # based on https://circleci.com/docs/2.0/yarn/
            - name: Running unit tests
              run: yarn test
            - name: Build
              run: yarn build
            - name: Generate .d.ts files
              run: yarn generate-types
            - name: Release
              run: yarn release
              env:
                  GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
                  GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
            # - name: Push tags
            #   run: git push origin --tags
        env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
