name: Run tests

on:
    # push:
    pull_request:
        branches: [main, beta]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn install --immutable # based on https://circleci.com/docs/2.0/yarn/
            - name: Running unit tests
              run: yarn test
            - name: Running code coverage
              run: yarn coverage
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
